imports:
    - { resource: '../areas/*.yaml' }

toolbox:
    area_block_configuration:
        groups:
            -   name: 'Team Modules'
                elements:
                    - 'team_list'
                    - 'team_congratulation'
            -   name: 'Event Modules'
                elements:
                    - 'event_countdown'
                    - 'event_list'
            -   name: 'Fact Modules'
                elements:
                    - 'fact'
    areablock_restriction:
        default_section:
            allowed:
                - 'team_list'
                - 'team_congratulation'
                - 'event_countdown'
                - 'event_list'
                - 'fact'
