pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    nextEvent--image:
                        items: {  }
                        medias: {  }
                        name: nextEvent--image
                        description: ''
                        group: ''
                        format: SOURCE
                        quality: 85
                        highResolution: null
                        preserveColor: false
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1730378673
                        creationDate: 1730378660
                        preserveAnimation: false
