services:
    App\Document\Areabrick\TeamList:
        parent: ToolboxBundle\Document\Areabrick\AbstractAreabrick
        tags:
            - {
                name: toolbox.area.brick,
                id: 'team_list',
                title: 'Team List',
            }
