pimcore:
    general:
        domain: localhost
        redirect_to_maindomain: false
        valid_languages:
            - en
            - de
            - fr
        fallback_languages:
            en: ''
            de: ''
            fr: ''
        required_languages:
            - en
            - de
            - fr
        default_language: en
        debug_admin_translations: true
    documents:
        versions:
            days: null
            steps: null
        error_pages:
            default: ''
            localized:
                en: ''
                de: ''
                fr: ''
    objects:
        versions:
            days: null
            steps: null
    assets:
        versions:
            days: null
            steps: null
    email:
        debug:
            email_addresses: simon.drohsen@instride.ch
