pimcore_static_routes:
    definitions:
        1719e53d-84bb-4ed6-b7e6-ba76d50a6f14:
            name: fact
            pattern: /fact/
            reverse: ''
            controller: 'App\Controller\FactController::action'
            variables: ''
            defaults: ''
            siteId: {  }
            methods:
                - GET
            priority: 1
            creationDate: 1732105490
            modificationDate: 1732717305
