pimcore_static_routes:
    definitions:
        4c776377-bc04-4a83-a2a5-16107a895e5a:
            name: birthday_congratulation
            pattern: /birthday-congratulation/
            reverse: ''
            controller: 'App\Controller\BirthdayCongratulationController::action'
            variables: ''
            defaults: ''
            siteId: {  }
            methods:
                - GET
            priority: 1
            creationDate: 1732105291
            modificationDate: 1732723150
