pimcore_static_routes:
    definitions:
        680a9c85-a24b-4eb6-8939-7d98b10f80f6:
            name: event_list
            pattern: /event-list/
            reverse: ''
            controller: 'App\Controller\EventListController::action'
            variables: ''
            defaults: ''
            siteId: {  }
            methods:
                - GET
            priority: 1
            creationDate: 1732105411
            modificationDate: 1732723175
