pimcore_static_routes:
    definitions:
        949438d8-efeb-4c3c-a17c-10eb73dac1ea:
            name: event_countdown
            pattern: /event-countdown/
            reverse: ''
            controller: 'App\Controller\EventCountdownController::action'
            variables: ''
            defaults: ''
            siteId: {  }
            methods:
                - GET
            priority: 1
            creationDate: 1732105447
            modificationDate: 1732723176
